# Generated by Django 4.0 on 2021-12-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assigned_to',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.customer_order'),
        ),
        migrations.AlterField(
            model_name='completes',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.customer_order'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.location'),
        ),
    ]
