# Generated by Django 4.0 on 2021-12-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_assigned_to_order_id_alter_completes_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='has_as_inventory',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='has_as_inventory',
            unique_together={('address', 'upc')},
        ),
    ]
