# Generated by Django 4.0 on 2021-12-17 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_has_as_inventory_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ord_includes',
            unique_together={('order_id', 'upc')},
        ),
    ]
