# Generated by Django 4.0 on 2021-12-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_stock_order_includes_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='salt',
        ),
        migrations.AlterField(
            model_name='account',
            name='salted_pwd_hash',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='ship_includes',
            unique_together={('tracking_no', 'upc')},
        ),
    ]
