# Generated by Django 4.0 on 2021-12-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_account_salt_alter_account_salted_pwd_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongs_to',
            name='employee_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='belongs_to',
            name='phone_number',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.customer'),
        ),
    ]
