# Generated by Django 4.0 on 2021-12-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_belongs_to2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Belongs_to2',
        ),
    ]
