# Generated by Django 4.0 on 2021-12-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_belongs_to2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='salted_pwd_hash',
            field=models.BinaryField(max_length=60),
        ),
    ]
