# Generated by Django 4.0 on 2021-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_salted_pwd_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='employee_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
